language: ruby
rvm:
  - 2.3.0
install:
  - cp config/database.example.yml config/database.yml
  - bundle install --jobs=3 --retry=3 --no-deployment
  - bundle exec rake db:create db:migrate db:seed
build: bundle exec rspec
